server:
  port: 8000
  servlet:
    context-path: /demo

# datasource
spring:
  profiles:
    include: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pch.user.model.do


secure:
  ignored:
    urls: #安全路径白名单
      #      - /**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /doc.html
      - /webjars/**
      - /v2/api-docs
      - /user/register
      - /user/login
#      - /**/v2/api-docs
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.ico
#      - /webjars/springfox-swagger-ui/**
#      - /actuator/**
#      - /druid/**

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: my_user_demo #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头
  iss: pch #签发人

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50
