server:
    port: 8000
    servlet:
        context-path: /demo

# datasource
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tb_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.pch.user.po

logging:
    level:
         com:
            pch: info

secure:
    ignored:
        urls: #安全路径白名单
            - /**
            - /swagger-ui.html
            - /swagger-resources/**
            - /swagger/**
            - /**/v2/api-docs
            - /**/*.js
            - /**/*.css
            - /**/*.png
            - /**/*.ico
            - /webjars/springfox-swagger-ui/**
            - /actuator/**
            - /druid/**
            - /admin/login
            - /admin/register
            - /admin/info
            - /admin/logout
            - /minio/upload

jwt:
    tokenHeader: Authorization #JWT存储的请求头
    secret: mall-admin-secret #JWT加解密使用的密钥
    expiration: 604800 #JWT的超期限时间(60*60*24*7)
    tokenHead: 'Bearer ' #JWT负载中拿到开头