# datasource
spring:
  profiles:
    include: jpa
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 300
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
  redis:
    redisson:
      config: classpath:application-redisson.yml
  data:
#    elasticsearch:
#      elasticsearch:
#        #集群名称
#        cluster-name: elasticsearch
#        #节点
#        cluster-nodes: 127.0.0.1:9300
    mongodb:
      uri: mongodb://127.0.0.1:27017/pch
