# \u9879\u76EE\u5730\u5740
server:
    port: 8000
    servlet:
        context-path: /demo

# datasource
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tb_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver

    mybatis:
        mapper-locations: classpath:mapper/*.xml
        type-aliases-package: com.pch.user.po

    logging:
        level:
            com:
                pch: info

jwt:
    tokenHeader: Authorization #JWT\u5B58\u50A8\u7684\u8BF7\u6C42\u5934
    secret: mall-admin-secret #JWT\u52A0\u89E3\u5BC6\u4F7F\u7528\u7684\u5BC6\u94A5
    expiration: 604800 #JWT\u7684\u8D85\u671F\u9650\u65F6\u95F4(60*60*24*7)
    tokenHead: 'Bearer ' #JWT\u8D1F\u8F7D\u4E2D\u62FF\u5230\u5F00\u5934