server:
  port: 8000
  servlet:
    context-path: /demo

# datasource
spring:
  profiles:
    include: dev

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.pch.user.po


secure:
  ignored:
    urls: #安全路径白名单
      #      - /**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /doc.html/**
      - /user/register
      - /user/login
#      - /**/v2/api-docs
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.ico
#      - /webjars/springfox-swagger-ui/**
#      - /actuator/**
#      - /druid/**

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: my_user_demo #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头