server:
  port: 8000
  servlet:
    context-path: /demo

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    maxActive: 300
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect


#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.pch.user.po


secure:
  ignored:
    urls: #安全路径白名单
      #      - /**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /user/register
      - /user/login
#      - /**/v2/api-docs
#      - /**/*.js
#      - /**/*.css
#      - /**/*.png
#      - /**/*.ico
#      - /webjars/springfox-swagger-ui/**
#      - /actuator/**
#      - /druid/**

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: my_user_demo #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头